### ISSUE TITLE
ItunesItem doesn't have Core/Item elements

### ISSUE THREAD

**Issue by sas1024** [marcw/rss-writer#2]
ItunesItem doesn't have elements from Core/Item.
For example: title, description, link etc.

I think, Core/Item must be a trait - then we can easy use it in all another Items.

**Comment by sas1024** [comment]
ohhhhh... I'm so sorry! ItunesItem can be connected with addExtension method...

**Comment by marcw** [comment]
No worries. This lib indeed uses composition a lot. Feel free to ask any question you got!
